---
title: "Presentación"
author: "César Puebla R."
date: "01-01-2023"
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: true
      
#Nivel 1
##Nivel 2
###Nivel 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Soy Sociólogo e Ingeniero de Ejecución en Prevención de Riesgos con más de 9 años de experiencia en análisis de datos, automatización de reportes, diseño y visualización de información. Me considero metódico, proactivo, y disfruto trabajar en equipos multidisciplinarios para abordar desafíos tanto públicos como privados. He coordinado proyectos en la Universidad de Chile, trabajado en la SEREMI Educación de la Región Metropolitana, en el Consejo para la Transparencia, asesorado municipalidades, fundaciones y actualmente me desempeño en el Instituto Nacional de Estadísticas de Chile (INE).

# Contenido {.unnumbered}

La presente documentación tiene como objetivo mostrar el uso de *script*, archivos, así como tablas de entrada y salida, así como disponerlas para que cualquier persona que quisiera pudiera replicarlo. 

Dicho lo anterior, se recalca que como portafolio la finalidad de esta documentación es mostrar algoritmos, funciones, imágenes y bases de datos, sin embargo, los resultados o el producto de dichos documentos, no tienen la finalidad de ser generalizables o extrapolables. 

Se profundizará en 5 contenidos:

- Problema y pregunta de investigación
- Procesamiento de la información.
- Dashboard: Muestra el complemento entre Shinyapp, FlexDashboard y el uso de Rmarkdown
- Reportes Automatizados: Generación de documentos que se actualizan de acuerdo a la necesidad del usuario.
- Estadística multivariada: Tabla que reúne los datos de los estudiantes de las cohortes estudiadas (2004 a 2008), en tanto, el alcance es hasta el año 2018. 
- Tablas y Gráficos:Tabla que resume los datos de los estudiantes de la tabla de trayectorias.
- Anexos: Detalle del los algoritmos utilizados.



## Uso de GitHub y RMarkdown {.unnumbered}

Por otra parte, para ver el repositorio completo, así como la estructura de carpetas y archivos que lo componen les recomiendo visitar el siguiente link [Repositorio en GitHub](https://github.com/Pueblac/portafolio) que se va actualizando periódicamente. En tanto, para la redacción se utilizó  [R Mardown](https://rmarkdown.rstudio.com/) ya que admite formatos de salida estáticos y dinámicos, incluyendo HTML, PDF, MS Word, Beamer, diapositivas HTML5, folletos al estilo Tufte, libros, paneles dinámicos, entre otros.   

## Control de versiones {.unnumbered}

Para el control de cambios del presente proyecto se utiliza [Git](https://git-scm.com/), el cual registra las distintas versiones de un archivo (o conjunto de archivos). 


## Procesamiento en Rstudio

Para la secuencia de comandos utilizados en el procesamiento de información y cálculo de métricas, se utilizó la versión de escritorio de Rstudio, que permite localmente obtener resultados de la sintaxis, codificación e indentación del código de R. 

Siendo necesario añadir que previa instalación de Rstudio, se debe instalar entorno de 'R', que compila y ejecuta directamente el lenguaje R para Windows y/o para Rstudio. Ambos links se encuentran a continuación:


- [R](https://cran.r-project.org/bin/windows/base/) - HTML a la versión instalable y ejecutable de R 4.0.2. 

- [Rstudio](https://rstudio.com/products/rstudio/download/#download) - HTML a la descarga de la versión más reciente de Rstudio.)


## Por qué no se utilizó SQLSever

Existe una transición en el procesamiento de los datos y la carga de origen. Durante los años previos, el análisis de los datos se realizaba  en [SQLServer 2012 Standar versión 6.3.9600](https://www.microsoft.com/en-us/download/details.aspx?id=56040) (en adelante SQLServer), en complemento con [RStudio versión 1.1.463](https://rstudio.com/products/rstudio/older-versions/). Actualmente se realiza todo en la última versión de Rstudio.  

La principal razón que motivó el cambio, es debido a que al ser Rstudio requiere tres cosas para conectarse a SQLServer:

a. Una conexión segura que permita la comunicación entre máquinas: Lo cual estaba asegurado mediante el servicio otorgado por la VPS (escritorio remoto), contrato que cumplió el periodo acordado y por tanto, fue necesario migrar a un sistema que permitiera realizar cálculos mediante un servidor local.

b. Drivers instalados para R server: Los cuales en el año 2020 dejaron de ser proporcionados mediante el paquete "RevoScaleR", que permite establecer la conexión entre Rstudio y SQLServer. Entre las limitaciones encontradas se comprobó que:  
  - El paquete "RevoScaleR" estaba destinado a ser utilizado con un servidor remoto, para procesar el conjunto de datos, sin embargo, se necesita un servidor remoto y una edición completa de SQLServer. 
  - El paquete no es de fácil instalación, ejecutando "install.packages ("RevoScaleR") como la mayoría de los paquetes R.
  - Está disponible solo a través de Microsoft R Client, la distribución de R para ciencia de datos.
  - Está hecha para la versión R 3.5.2, en tanto, la mayor parte de los paquetes utilizados para el análisis corresponden a la versión 4.0.2.

Por las razones anteriores, que las tablas que se utilicen vas a ser transformadas a formato RDS. Este formato es especialmente útil cuando se tienen datos grandes que necesitan ser cargados con frecuencia, ya que el tiempo de lectura y escritura de archivos RDS es generalmente más rápido que el de otros formatos como CSV o Excel.






