---
title: "Tabla de Observaciones"
author: "César Puebla R."
date: "10-07-2020"
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: true
      
#Nivel 1
##Nivel 2
###Nivel 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 5. Observaciones

Constituyen tablas el resultado del proceso de transformación de datos desde la tabla de trayectorias, resumiendo la información por cada uno de los estudiantes.   Es decir, cada observación es un estudiante en un año, encontrándose definido por el par (MRun, Año). 


## 5.1 Composición de la tabla de trayectorias

Para construir la tabla de  trayectorias educativas, como construir la tabla de Observaciones, Los datos provienen de dos fuentes administrativas:

Fuente | 	Longitud	 | Origen	|
-------|-------------|--------|
Matrículas	|2004 - 2018	|MINEDUC	|
Rendimiento	| 2004 - 2018	| MINEDUC |


Al igual que en la tabla de trayectorias, hay limitaciones y requiere de mayor validación. Es decir, a medida que se han visto los diversos resultados que tiene una versión más actualizada que la anterior, se encuentran detalles que interpelan directamente el código. 


## 5.2 Organización del contenido {.tabset}

A diferencia de la tabla de trayectorias, La tabla de salida de la tabla de observaciones, es el producto de la ejecución de varios script, teniendo solo una tabla de salida.


### Script {#script}

En este caso se utilizará el Script "Tab_Observaciones30062020.R"  y se encuentra en la siguiente ubicación:

[Tab_Observaciones30062020.R](https://drive.google.com/file/d/1usDM8PO_qvzyWoRLlcBT01q5sPkYxz3x/view?usp=sharing)

Se prefirió expresarlo en el [Anexo | Tabla de Observaciones](anexos.html#tobs)


### Tablas de salida


1. [Tabla observaciones 3006](https://drive.google.com/file/d/1NRN3WajjU84Fq3yPX6X8H8IfqGImD6DW/view?usp=sharing)
2. [GLosario](https://docs.google.com/spreadsheets/d/1m57CnQNqpTFkdDmnS7sHoJTZrU6l5VM6EecZFcr7wNY/edit?usp=sharing)

